# Generated by Django 5.0.3 on 2024-03-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_subjectmarks_student_studentrank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrank',
            unique_together={('student_rank', 'date_of_report_generation')},
        ),
    ]
