# Generated by Django 5.0.3 on 2024-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_alter_studentrank_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='date_of_report_generation',
            field=models.DateField(auto_created=True),
        ),
    ]
